spring:
  application:
    name: siswa-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_msig_student
    username: dicka
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /siswa-service
  port: 8081