spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: siswa-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_msig_student
    username: dicka
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /siswa-service
  port: 8081
feignClient:
  backoffice-service:
    rolesIdSiswa: R003
    host: backoffice-service
    fetchRolesById: /backoffice-service/backoffice-service/v1/fetch-roles-byid/{id}
